'use client';
import {useState,useRef,useEffect} from 'react';
import {ArrowUpRight,RotateCcw,Camera,Layers3,Focus,X,Play,Pause,Plus,Minus,Smartphone,Aperture,Cpu,Battery,Volume2,Radio,Zap,Info} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {useExploreTool} from './agent-tools';
import {Slider} from '@/components/ui/slider';
import Scene from './scene';
import {parts,journey} from './parts';
const icons=[Smartphone,Layers3,Aperture,Cpu,Battery,Radio,Volume2,Zap,Layers3,Focus];
export default function Home(){
 const [explode,setExplode]=useState(0),[selected,setSelected]=useState<string|null>(null),[isolated,setIsolated]=useState(false),[color,setColor]=useState('silver'),[rotate,setRotate]=useState(false),[view,setView]=useState(0),[zoom,setZoom]=useState(0),[step,setStep]=useState(-1),[sources,setSources]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState('');
 const timer=useRef<ReturnType<typeof setInterval>|null>(null);const part=parts.find(p=>p.id===selected);
 useExploreTool(i=>{stop();if(i.assembly)setSelected(i.assembly);setIsolated(i.isolate??false);if(i.explode!==undefined)setExplode(i.explode);else if(i.assembly)setExplode(75)},parts.map(p=>p.id));
 function stop(){if(timer.current)clearInterval(timer.current);timer.current=null;setStep(-1)}
 function reset(){stop();setExplode(0);setSelected(null);setIsolated(false);setRotate(false);setView(v=>v%2===0?v+2:v+1);setZoom(0)}
 function select(id:string){stop();setSelected(id);setIsolated(false);setExplode(e=>Math.max(e,72))}
 function photo(){stop();setIsolated(false);setRotate(false);setExplode(82);setStep(0);setSelected('camera');let s=0;timer.current=setInterval(()=>{s++;if(s>=journey.length){if(timer.current)clearInterval(timer.current);timer.current=null;return}setStep(s);setSelected(journey[s].part)},3000)}
 useEffect(()=>()=>{if(timer.current)clearInterval(timer.current)},[]);
 return <main className="studio">
 <header className="topbar"><a className="brand" href="/" aria-label="Inside iPhone home"><span className="brand-mark"><Layers3 size={20}/></span>inside<span className="brand-slash">/</span><span className="brand-product">iPhone</span></a><div className="edition">AN INTERACTIVE STUDY <span>—</span> 001</div><button className="source-button" onClick={()=>setSources(true)}>About this study <ArrowUpRight size={15}/></button></header>
 <section className="workspace" aria-label="Interactive iPhone explorer">
 <div className="scene-wrap"><Scene explode={explode/100} selected={selected} isolated={isolated} color={color} rotating={rotate} view={view} zoom={zoom} step={step} onSelect={select} onReady={()=>setReady(true)} onError={setError}/></div>
 <div className="intro"><div className="eyebrow"><span className="live-dot"/> I N S I D E   i P H O N E</div><h1>iPhone 17 Pro<span>Anatomy of precision.</span></h1><p></p><div className="finish"><span>FINISH</span><div className="swatches">{[['orange','Cosmic Orange'],['silver','Silver'],['blue','Deep Blue']].map(([c,label])=><button key={c} style={{'--swatch':c==='orange'?'#d77b42':c==='silver'?'#d0d1d2':'#34435d'} as React.CSSProperties} className={'swatch '+(color===c?'active':'')} aria-label={label} aria-pressed={color===c} onClick={()=>setColor(c)}/>)}</div><small>{color==='orange'?'Cosmic Orange':color==='silver'?'Silver':'Deep Blue'}</small></div></div>
 <aside className="parts-panel"><div className="panel-label">ASSEMBLIES <span>10</span></div><div className="parts-list">{parts.map((p,i)=>{const Icon=icons[i];return <button key={p.id} onClick={()=>select(p.id)} className={'part-row '+(selected===p.id?'selected':'')} aria-pressed={selected===p.id}><span className="part-number">{String(i+1).padStart(2,'0')}</span><Icon size={16}/><span>{p.name}</span><span className="part-arrow">↗</span></button>})}</div><div className="panel-note">Select a part to look closer.</div></aside>
 {!ready&&!error&&<div className="loading" role="status">Preparing your perspective…</div>}{error&&<div className="loading error" role="alert">{error}<button onClick={()=>location.reload()}>Try again</button></div>}
 <div className="right-tools"><button onClick={()=>setView(v=>v+1)} aria-label="Flip phone" title="Flip phone"><Smartphone size={18}/></button><button onClick={()=>setRotate(!rotate)} className={rotate?'active':''} aria-label={rotate?'Pause rotation':'Auto rotate'}>{rotate?<Pause size={18}/>:<RotateCcw size={18}/>}</button><span/><button onClick={()=>setZoom(z=>Math.min(z+1,3))} aria-label="Zoom in"><Plus size={18}/></button><button onClick={()=>setZoom(z=>Math.max(z-1,-2))} aria-label="Zoom out"><Minus size={18}/></button><button onClick={reset} aria-label="Reset view"><Focus size={18}/></button></div>
 {part?<aside className="inspector"><div className="inspector-top"><span>{part.category}</span><button onClick={()=>{stop();setSelected(null);setIsolated(false)}} aria-label="Close component details"><X size={16}/></button></div><span className="detail-number">{String(parts.indexOf(part)+1).padStart(2,'0')} / 10</span><h2>{part.name}</h2><div className="detail-rule"/><p>{part.description}</p><dl><dt>ROLE</dt><dd>{part.role}</dd><dt>IN THIS STUDY</dt><dd>Illustrative assembly</dd></dl><button className="isolate" aria-pressed={isolated} onClick={()=>{stop();setIsolated(!isolated)}}><Focus size={16}/>{isolated?'Show all assemblies':'Isolate assembly'}</button></aside>:<aside className="invitation"><span>+</span><p>Nothing is ordinary<br/>when you look inside.</p><button onClick={()=>setExplode(100)}>Take it apart <ArrowUpRight size={17}/></button></aside>}
 {step>=0&&<div className="journey-card" aria-live="polite"><div className="journey-top"><span>THE PHOTO JOURNEY</span><button aria-label="Close photo journey" onClick={stop}><X size={16}/></button></div><div className="journey-progress">{journey.map((_,i)=><button aria-label={'Photo journey step '+(i+1)} key={i} className={i<=step?'passed':''} onClick={()=>{stop();setStep(i);setSelected(journey[i].part)}}/>)}</div><h2><span>0{step+1}</span>{journey[step].title}</h2><p>{journey[step].description}</p><small>Simplified sequence · not a timing simulation</small></div>}
 <div className="viewport-hint">↔ &nbsp; Drag to orbit <span>·</span> Scroll to zoom</div>
 <div className="control-dock"><div className="explode-control"><div className="slider-heading"><button onClick={()=>{stop();setIsolated(false);setExplode(explode>50?0:100)}}><Layers3 size={16}/>{explode<1?'Reveal the inside':'Exploded view'}</button><output>{Math.round(explode)}<span>%</span></output></div><Slider aria-label="Explode phone assemblies" value={[explode]} min={0} max={100} step={1} onValueChange={v=>{stop();setIsolated(false);setExplode(Array.isArray(v)?v[0]:v)}}/><div className="slider-captions"><span>Assembled</span><span>Every layer</span></div></div><div className="dock-divider"/><button className="photo-button" onClick={photo}><Camera size={18}/><span>Follow a photo</span><Play size={12} fill="currentColor"/></button><button className="reset" onClick={reset} aria-label="Reset all"><RotateCcw size={17}/></button></div>
 </section><footer><span><span className="footer-dot"/> REAL-TIME 3D <b> / </b> BUILT WITH ASTRA</span><button onClick={()=>setSources(true)}>Illustrative internals · Independent study <Info size={13}/></button><span className="footer-right">DESIGNED TO BE EXPLORED <ArrowUpRight size={13}/></span></footer>
 <Dialog open={sources} onOpenChange={setSources}><DialogContent className="about-modal" showCloseButton={false}><button className="modal-close" onClick={()=>setSources(false)} aria-label="Close about"><X/></button><span className="eyebrow">ABOUT THIS STUDY</span><DialogTitle>A closer look.<br/>An independent perspective.</DialogTitle><DialogDescription>An original, browser-rendered interpretation of iPhone 17 Pro. Exterior proportions and feature descriptions reference Apple. Internal shapes, placement, connectors and the photo journey are simplified educational illustrations, not a repair guide or an exact device scan.</DialogDescription><p>All 3D geometry is created in code. No Tesla or anatomy model assets are included.</p><div className="source-links">{[['https://stocksnap.io/photo/mountain-landscape-1YYGRD3S8N','Photo · Sergei Gussev / StockSnap (CC0)'],['https://www.apple.com/iphone-17-pro/specs/','Apple · Specifications'],['https://www.ifixit.com/News/113388/iphone-17-pro-teardown','iFixit · Teardown reference'],['https://github.com/ashemag/human-atlas','Interaction inspiration · Human Atlas'],['https://github.com/ashemag/model-x-studio','Interaction inspiration · Model X Studio']].map(([url,label])=><a key={url} href={url} target="_blank" rel="noreferrer">{label}<ArrowUpRight size={15}/></a>)}</div><small>iPhone is a trademark of Apple Inc. This study is not affiliated with or endorsed by Apple.</small><button className="isolate" onClick={()=>setSources(false)}>Back to exploring</button></DialogContent></Dialog>
 </main>
}


