export const parts=[
{id:'frame',name:'Aluminum unibody',category:'STRUCTURE',description:'The aluminum enclosure gives the phone its shape and helps distribute heat. Its raised camera plateau integrates the rear camera system into the body.',role:'Structural enclosure'},
{id:'display',name:'Super Retina XDR',category:'DISPLAY',description:'The 6.3-inch OLED display brings your photos back into view. Each pixel emits its own light, with ProMotion supporting adaptive refresh rates up to 120 Hz.',role:'Light, color and touch'},
{id:'camera',name:'Pro camera system',category:'OPTICS',description:'Three rear 48MP Fusion cameras offer different perspectives. Explore the layered lens illustration, then follow a photo from incoming light to the display.',role:'Collect light and capture detail'},
{id:'chip',name:'A19 Pro',category:'COMPUTE',description:'The A19 Pro combines CPU, GPU and Neural Engine capabilities. Image-processing hardware and software help transform captured sensor data into a finished photograph.',role:'Compute and image processing'},
{id:'battery',name:'Battery',category:'POWER',description:'A rechargeable lithium-ion battery stores energy for the display, cameras and processors. Its shape and markings here are illustrative, not service specifications.',role:'Stored electrical energy'},
{id:'coil',name:'MagSafe assembly',category:'WIRELESS',description:'Magnetic alignment helps position compatible accessories and wireless chargers. A receiver coil transfers energy through electromagnetic induction.',role:'Alignment and wireless charging'},
{id:'speaker',name:'Speaker assembly',category:'AUDIO',description:'An electrical signal drives a tiny moving diaphragm to produce sound. The chamber and grille help direct that sound out of the enclosure.',role:'Electrical signal to sound'},
{id:'port',name:'USB-C connector',category:'CONNECTION',description:'The USB-C port supports charging and wired data transfer. Small contacts connect the cable to the phone’s power and communication circuits.',role:'Wired power and data'},
{id:'thermal',name:'Vapor chamber',category:'THERMAL',description:'An Apple-designed vapor chamber helps spread heat from A19 Pro into the aluminum unibody. The copper layer here represents that thermal system.',role:'Distribute heat'},
{id:'haptic',name:'Taptic Engine',category:'FEEDBACK',description:'A compact actuator creates the precise vibrations you feel during touch interactions. The moving mass shown here is a simplified representation.',role:'Tactile feedback'}];
export const journey=[{part:'camera',title:'It starts with light.',description:'Light from the scene passes through a camera lens. Its optical elements focus that light onto the sensor.'},{part:'camera',title:'Light becomes a signal.',description:'Photosensitive pixels convert incoming light into electrical signals. These measurements become image data.'},{part:'chip',title:'A photograph takes shape.',description:'The image-processing pipeline combines and adjusts captured data for color, detail and exposure.'},{part:'display',title:'Back into light.',description:'The finished photograph appears on the OLED display. The journey ends where you can see it.'}];
